---
# name: ansible-molecule-images
# file: playbooks/vars/opensuse.yml

dockerfile:
  from: "{{ container_registry }}/{{ container_image }}"
  entrypoint: "/usr/lib/systemd/systemd"
  environment:
    container: docker
  package_update: "zypper -n update"
  package_install: "zypper -n install"
  packages:
    - bash
    - iproute2
    - python3
    - python3-xml
    - shadow
    - sudo
    - systemd
  package_clean: "zypper clean"
  commands:
    - find /etc/systemd/system /usr//lib/systemd/system -path 'sysinit.target.wants/*' -not -name '*systemd-tmpfiles*' -delete
    - rm -f /usr/lib/systemd/system/multi-user.target.wants/*
    - rm -f /etc/systemd/system/*.wants/*
    - rm -f /usr/lib/systemd/system/local-fs.target.wants/*
    - rm -f /usr/lib/systemd/system/sockets.target.wants/*udev*
    - rm -f /usr/lib/systemd/system/sockets.target.wants/*initctl*
    - rm -f /usr/lib/systemd/system/basic.target.wants/*
    - systemctl mask getty.service
    - touch /etc/sudoers && sed -ie 's/^\(Defaults\s*requiretty\)/#--- \1/' /etc/sudoers
